import java.io.*;
import java.util.*;
import java.util.Random.*;
import java.lang.Math.*;

/**
 *Think Java 3.12, Exercise 4
 *Jonathan Swotinsky
 */

public class GuessMyNumber{
	public static void main(String[] args){
		
		//Generate a random number.
		Random random = new Random();
		int number = random.nextInt(100)+1;
		
		//Ask the user to guess the number.
		System.out.println("I'm thinking of a number between 1 and 100");
		System.out.println("(including both). Can you guess what it is?");
		System.out.print("Type a number: ");
		Scanner in = new Scanner(System.in);
		int userNumber = in.nextInt();
						
		//Compare the user's guess to the random number generated by the program.
		int difference = Math.abs(userNumber - number);
		System.out.printf("Your guess is: %d\n",userNumber);
		System.out.printf("The number I was thinking of was: %d\n",number);
		System.out.printf("You were off by: %d\n",difference);
	}
}

